### ISSUE TITLE
회원 가입, 탈퇴 관련 오류

### ISSUE THREAD

**Issue by soobin-jeon** [wafflestudio21-5/team6-server#77]
1. "철수"라는 이름으로 가입하려고 하니 예상치 못한 오류가 발생하였다며 가입이 되지 않습니다. 이름을 "철수"에서 "김철수"로 바꾸니 가입이 되었습니다.
![스크린샷 2024-02-04 000022](https://github.com/wafflestudio21-5/team6-server/assets/142797788/0d0905e5-77cb-46e8-8868-843068c0d40d)

2. 회원 탈퇴를 누르니 다음 사진과 같이 "로그아웃 실패"라는 창이 뜹니다. 확인을 누르고 메인페이지로 돌아가면 그 다음 사진처럼 아무것도 뜨지 않습니다. 완전히 나갔다 다시 접속하면 계정자체는 없어진 것 같습니다.
![스크린샷 2024-02-04 000234](https://github.com/wafflestudio21-5/team6-server/assets/142797788/75fd8756-1b69-40f8-b22a-74c530a9049f)
![스크린샷 2024-02-04 000308](https://github.com/wafflestudio21-5/team6-server/assets/142797788/00fa7261-6970-4803-8b96-8ddcfc3167a5)

**Comment by ohsuhyeon0119** [comment]
확인했습니다!
