### ISSUE TITLE
[Bug] 회원가입 오류

### ISSUE THREAD

**Issue by YJ0513** [wafflestudio21-5/team6-server#78]
![회원가입오류](https://github.com/wafflestudio21-5/team6-server/assets/135787320/efd7f13c-964b-4828-b32c-43b1646712c3)

아이디 chldudwn, 비밀번호 1qaz2wsx3edc 로 회원가입할 때 예상치 못한 오류가 발생합니다.

**Comment by ohsuhyeon0119** [comment]
확인했습니다!
