### ISSUE TITLE
회원가입 관련 오류

### ISSUE THREAD

**Issue by gs20118** [wafflestudio21-5/team6-server#80]
UI와 인터렉트가 너무 잘 되어 있어서 좋았습니다.
특히 스포일러성 댓글을 읽지 않았을 경우에 좋아요를 하지못하게 하는 디테일에 감동했습니다.
그런데 회원가입을 할 경우에 비밀번호를 abcde12345로 굉장히 단순하게 작성하니 예상치 못한 오류가 발생했다고 나옵니다.

**Comment by ohsuhyeon0119** [comment]
확인했습니다
