### ISSUE TITLE
유저 페이지 팔로워 수 반영 등

### ISSUE THREAD

**Issue by jwchoi-kr** [wafflestudio21-5/team6-server#84]
1. 다른 사람의 유저 페이지에서 팔로우/팔로잉 버튼을 눌렀을 때 버튼의 label은 변경되지만 그 위에 팔로워 수는 바로 변경되지 않습니다! 
2. 마찬가지로 영화 페이지에서 별점을 매겼을 때 평균 별점에 바로 반영되지 않습니다!

**Comment by izone00** [comment]
바로 반영되도록 수정했습니다!
