### ISSUE TITLE
비정상적인 URL의 처리

### ISSUE THREAD

**Issue by jwchoi-kr** [wafflestudio21-5/team6-server#85]
https://d1vexdz72u651e.cloudfront.net/contents/123412341234와 같이 존재하지 않는 URL이 들어오면 '잘못된 요청입니다'라는 alert가 뜨고 헤더만 남아있습니다! 라우터 맨 아래에 path: "*" 을 root page로 navigate되도록 설정하면 되겠네요!

**Comment by izone00** [comment]
main페이지 or 이전페이지로 가도록 수정했습니다
