### ISSUE TITLE
로그아웃 오류

### ISSUE THREAD

**Issue by hyunoh604** [wafflestudio21-5/team6-server#87]
카카오 로그인 후 마이페이지에서 로그아웃을 해도 그대로 제 계정의 프로필이 떠있습니다

**Comment by izone00** [comment]
프로필이 그대로 떠 있지만 본인 계정 페이지로 나타나지 않고
다른사람 프로필을 보는 것처럼 나타나게 되있습니다.
프로필 수정 버튼이 나타나지않고 팔로우 버튼이 나타나면 잘 로그아웃이 됬을 거예요!
