### ISSUE TITLE
프로필 사진 에러

### ISSUE THREAD

**Issue by vitacpark** [wafflestudio21-5/team6-server#88]
프로필 사진 설정 시 이미지가 아닌 파일을 삽입할 시 1회엔 오류창이 뜨나, 2회차 이후엔 별 다른 에러 창이 없으나 이상하게 프로필 사진이 표시됩니다.
별 다른 필터링 없이 파일이 삽입되는 것으로 보입니다. 

<img width="447" alt="image" src="https://github.com/wafflestudio21-5/team6-server/assets/55388254/586cc185-efac-40e1-b4fc-f3668d114b4c">
<img width="79" alt="image" src="https://github.com/wafflestudio21-5/team6-server/assets/55388254/4955548a-d21c-475f-a458-f543d798fd7d">

**Comment by izone00** [comment]
image만 업로드 되도록 수정했습니다!
