### ISSUE TITLE
검색 문자열 길이 이슈

### ISSUE THREAD

**Issue by vitacpark** [wafflestudio21-5/team6-server#89]
검색어의 문자가 너무 길 경우 사이트를 탈출하는 오류가 있습니다. 

<img width="1269" alt="image" src="https://github.com/wafflestudio21-5/team6-server/assets/55388254/4cdf8b94-5491-47d6-855d-f6e273a9b22e">
<img width="1280" alt="image" src="https://github.com/wafflestudio21-5/team6-server/assets/55388254/73fd1aac-7121-4929-8be0-a7704e117060">

**Comment by izone00** [comment]
벗어나지 않도록 고쳤습니다!

**Comment by vitacpark** [comment]
<img width="1278" alt="image" src="https://github.com/wafflestudio21-5/team6-server/assets/55388254/b2c606de-7a88-4848-b4b9-5e1ada4f17f6">
몇 자 이상일 시에 ...으로 생략하는게 좋을 것 같습니다..! 수고 많으십니다~!
