### ISSUE TITLE
다른 사용자 프로필 조회 가능 오류

### ISSUE THREAD

**Issue by gunhee1113** [wafflestudio21-5/team6-server#92]
https://d1vexdz72u651e.cloudfront.net/users/160 와 같은 url에서 맨 뒤 숫자만 적절히 바꾸면 다른 사람의 프로필을 확인할 수 있는 버그가 있습니다.
- 제 계정입니다.
![image](https://github.com/wafflestudio21-5/team6-server/assets/122969040/028c1053-c78a-412b-a148-af93cc9413d6)

- 다른 사람의 계정도 조회됩니다.
![image](https://github.com/wafflestudio21-5/team6-server/assets/122969040/fc90e19a-ec29-4f53-8d04-b99860a361db)

**Comment by ohsuhyeon0119** [comment]
다른 사람의 프로필을 확인할 수 있는 건 왓챠피디아에 있었던 의도한 기능입니다 본인 계정이 아니면 몇몇 ui가 달라지는걸 확인하실 수 있습니다
